### ISSUE TITLE
Getting graphics under qemu?

### ISSUE THREAD

**Issue by DylanBartlett** [crops/poky-container#21]
I've created a core-image-sato ARM build using the container. I'd now like to emulate it but I'm getting a "`Could not initialize SDL(No available video device)`" error.
Running the nographic option lets me boot to a login prompt but ideally, I need to get graphics working.
I tried using the publicvnc option but a server never starts and the system never boots.

Is this possible under the container?

**Comment by rewitt1** [comment]
Pull request https://github.com/crops/poky-container/pull/2 was meant to allow for this type of workflow. It was never merged because there are no tests for it.

And there is a fix needed in the yocto-dockerfiles repo for it to work.

If you're still interested in this let me know and I'll try to find time to get all the changes into the appropriate places.

**Comment by rewitt1** [comment]
@DylanBartlett,

Ignore my last comment which I deleted. I wasn't aware of the *publicvnc* option that had been added to runqemu. I tested it out and it does work.

The reason you don't see a vnc server is because it is built into qemu. When you run with the *publicvnc* option, you will only get a small amount of output on the terminal. All of the rest will go to the vnc server.

However, you will also need to redirect the ports from the container to the outside. For example here is how I started the container:

```
docker run -it --rm -p 127.0.0.1:20000:5900 crops/poky
```

After that you should see all the output when you connect your vnc client to port 20000, or whatever you decided to use.

**Comment by DylanBartlett** [comment]
Ah, thanks for pointing that out to me rewitt1. I wasn't aware I had to forward the port like that. I'll try this out when I try working on my own Yocto layers.
