### ISSUE TITLE
is not possible to know password

### ISSUE THREAD

**Issue by ghost** [crops/poky-container#26]
Is very good so i dont know how use

is not possible to know password

**Comment by rewitt1** [comment]
Since no one ever responded to this, and there isn't a clear question, I'm going to close this.

**Comment by mixaz** [comment]
pokyuser@7d3f2f3087d5:/workdir$ apt-get install bc
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
pokyuser@7d3f2f3087d5:/workdir$ sudo apt-get install bc
[sudo] password for pokyuser: 
Sorry, try again.
[sudo] password for pokyuser: 
Sorry, try again.
[sudo] password for pokyuser: 
sudo: 3 incorrect password attempts

What is the password for pokyuser?

**Comment by rewitt1** [comment]
Hi @mixaz,

There is no password, but the password is in the ***locked*** state. So you can't switch to pokyuser using a password.

That being said, even if you could use the password, you still wouldn't be able to use sudo, because pokyuser isn't in the ***sudoers*** file.

If you want to perform something as root the easiest way is to probably start your container, and then run the command below in a different shell. CONTAINERID can be retrieved from ```docker ps``` or is the name you chose for the container:
```
docker exec -it --user=root CONTAINERID bash
```

From that shell you could run ```apt-get```, change the sudoers file, change the password for pokyuser or any other things that require root privileges.

**Comment by mixaz** [comment]
@rewitt1 I already reviewed a similar issue here where you explained that, but thanks anyway
