### ISSUE TITLE
how to display qemu in container by graphics

### ISSUE THREAD

**Issue by cvnovice95** [crops/poky-container#35]

**Comment by rewitt1** [comment]
Hi @fengjinyuan,

Here is a way I've used to get graphical qemu output using the _publicvnc_ argument with _runqemu_.

1. Forward the vnc port when you start the container. Using docker run, add **-p 5900:5900** to the command line. For example:
``
docker run -p 5900:5900 ...
``

2. Setup your build environment as normal.

3. Start qemu using _runqemu_ and use the _publicvnc_ argument.
``
pokyuser@241af804767d:/build$ runqemu slirp publicvnc core-image-sato
``

4. Outside of the container on the host, use a vnc client to connect to the vncserver that was started by qemu. For example:
``
~% vncviewer -FullColor localhost:5900
``

You could also start a vncserver manually inside the container rather than using the one builtin to qemu. But if these instructions work for you, I don't want to overload you with options.

**Comment by rewitt1** [comment]
Since there has been no further discussion, I am closing the issue.
