### ISSUE TITLE
python-setuptools-scm in bionic is too outdated for some workflows 

### ISSUE THREAD

**Issue by jfernandz** [crops/poky-container#88]
Hi guys, I've noticed that `setuptools-scm` package in `bionic` it's pretty outdated so `version` cannot be determined at build time from scm(git) tags ... I've tested my software with a newer setuptools-scm version and it works as expected, but when I install `python3-setuptools-scm` and run `python3 setup.py sdist` inside the crops/poky container the setuptools sets `0.0.0` version.

Not sure if some fix is possible for this issue or I should wait until your crops/poky image be based over some newer Ubuntu version.

**Comment by moto-timo** [comment]
We actually build a matrix of [~14 distro/versions](https://hub.docker.com/r/crops/poky/tags). You can choose a newer Ubuntu release:  `docker pull crops/poky:ubuntu-22.04` or `docker pull crops/poky:ubuntu-20.04`

The default (`crops/poky:latest`) is still Ubuntu 18.04 because MANY vendors are still stuck on requiring that version. And yes, it is 2022.

**Comment by jfernandz** [comment]
I didn't notice this, thank you very much, I've tested `crops/poky:debian-11` and it's a little bit updated, sure :blush:

Thank you very much!
