### ISSUE TITLE
rocko based distro doesn't build any more

### ISSUE THREAD

**Issue by dradic2** [crops/poky-container#92]
Hello,

I was using your container to build a rocko based distro.
Since a week or so it stopped building, breaking very early in the process with the following message
`ImportError: cannot import name 'MutableMapping' from 'collections'`
This implies that the Python version has been updated.
Is there a quick fix for this or should I search for some other solution?

Regards,
Dusan

**Comment by moto-timo** [comment]
The design goal of the crops project has always to be building the currently supported Yocto Project releases. When the [minimum requirement for Python changed to 3.8](https://lore.kernel.org/bitbake-devel/20221211173345.22120-1-richard.purdie@linuxfoundation.org/), we had to [update the build-tools tarball](https://github.com/crops/yocto-dockerfiles/commit/36d6fdb42f48106612b81076da1a78d84fe3a57b) used in the older distro containers.

Rocko has been out of support since [2018](https://wiki.yoctoproject.org/wiki/Releases). You are welcome to go back in git history and build an older container that supports your needs.

The fact that the containers have worked for older EOL Yocto Project releases for so long was just luck. Not plan.

**Comment by moto-timo** [comment]
FWIW, we still have some old EOL containers available:
https://hub.docker.com/r/crops/poky-eol/tags

But those are not rebuilt (most likely cannot be built anymore) and have no security updates.

**Comment by dradic2** [comment]
Hi Tim, 

well that explains it :)
Thank you for a quick and helpful response!

Regards,
Dusan
