### ISSUE TITLE
can poky-container use "runqemu"

### ISSUE THREAD

**Issue by zhen9910** [crops/poky-container#96]
I got this error when use "runqemu" to start qemux86-64
```
pokyuser@4117b5b5e2bf:~/yocto/build-minimal$ runqemu qemux86-64 nographic
runqemu - INFO - Running MACHINE=qemux86-64 bitbake -e ...
runqemu - ERROR - TUN control device /dev/net/tun is unavailable; you may need to enable TUN (e.g. sudo modprobe tun)
runqemu - INFO - Cleaning up
runqemu - INFO - Host uptime: 56244.79

root@4117b5b5e2bf:/home/yoctouser# modprobe tun
modprobe: FATAL: Module tun not found in directory /lib/modules/5.10.102.1-microsoft-standard-WSL2
```
So, can poky-container use "runqemu"?
It looks like this kernel does not include the tun module, so qemu cannot work

**Comment by hntu1995** [comment]
I am having the same problem here, do you figure out how to solve this one

**Comment by moto-timo** [comment]
This is very complicated, because it depends on numeric GID from the host, since the container does not have the /dev/* which qemu needs. So every single distro decides to use different names for the GID for netdev or graphics or whatever. So those MUST be passed in as NUMERIC values to the container in order for runqemu to work. This is beyond any reasonably simple path to making it work. If you have a better proposal that will work for EVERY HOST and every single flavor of distro/version container we produce, please send a pull request.

**Comment by moto-timo** [comment]
Closing as this is not likely to be possible.

**Comment by fifv** [comment]
I tried https://github.com/crops/poky-container/issues/11#issuecomment-287434112
and it works
```
runqemu qemux86-64 slirp nographic
```
